{
 "title": "Full Text Search - ADX",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Data Source",
    "query": "grafana-azure-data-explorer-datasource"
   },
   { "name": "search", "label": "Text To Search", "query": "error" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Full Text Search Dashboard\nThis Dashboard can run a full text search against all logs and metrics collected by ADX and return the relevant results.\n\nThe search is:\n1. Case insensitive \n2. Uses the regex pattern of \\*<SEARCH QUERY>\\* to allow for non exact matches\n3. Based on the Timeframe selected at the top of the dashboard"
   }
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log Results",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "database": "openteldb",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "OTELLogs\r\n| where $__timeFilter(Timestamp)\r\n| search Body: \"*${search}*\"\r\n| extend BodyJson = parse_json(Body)\r\n| extend Namespace = tostring(BodyJson[\"kubernetes_namespace_name\"])\r\n| extend Pod = tostring(BodyJson[\"kubernetes_pod_name\"])\r\n| extend Node = tostring(BodyJson[\"kubernetes_host\"])\r\n| extend PodIP = tostring(BodyJson[\"kubernetes_pod_ip\"])\r\n| extend Stream = tostring(BodyJson[\"stream\"])\r\n| extend Log = tostring(BodyJson[\"log\"])\r\n| where isnull(BodyJson[\"KubeEventType\"]) or BodyJson[\"KubeEventType\"] == \"\"\r\n| project Timestamp, Namespace, Pod, PodIP, Node, Stream, Log",
       "querySource": "raw"
      }
     ]
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kubernetes Events Results",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "database": "openteldb",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "OTELLogs\r\n| where $__timeFilter(Timestamp)\r\n| search Body: \"*${search}*\"\r\n| extend BodyJson = parse_json(Body)\r\n| where isnotnull(BodyJson[\"KubeEventType\"])\r\n| extend Namespace = tostring(BodyJson[\"Namespace\"])\r\n| extend Name = tostring(BodyJson[\"Name\"])\r\n| extend Kind = tostring(BodyJson[\"Kind\"])\r\n| extend FirstSeen = tostring(BodyJson[\"FirstSeen\"])\r\n| extend Count = tostring(BodyJson[\"Count\"])\r\n| extend KubeEventType = tostring(BodyJson[\"KubeEventType\"])\r\n| extend LastSeen = tostring(BodyJson[\"LastSeen\"])\r\n| extend Message = tostring(BodyJson[\"Message\"])\r\n| extend ReportingComponent = tostring(BodyJson[\"ReportingComponent\"])\r\n| extend Reason = tostring(BodyJson[\"Reason\"])\r\n| project Kind, Namespace, Name, FirstSeen, LastSeen, Count, KubeEventType, Message, Reason, ReportingComponent",
       "querySource": "raw"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metric Results",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "database": "openteldb",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| search \"*${search}*\" \r\n| extend Namespace = coalesce(\r\n    tostring(parse_json(ResourceAttributes)[\"k8s.namespace.name\"]),\r\n    tostring(parse_json(MetricAttributes)[\"namespace\"]),\r\n    iif(\r\n        isnotempty(parse_json(ResourceAttributes)[\"server.address\"]),\r\n        split(tostring(parse_json(ResourceAttributes)[\"server.address\"]), \".\")[1],\r\n        \"\"\r\n    )\r\n  )\r\n| extend Pod = coalesce(\r\n    tostring(parse_json(ResourceAttributes)[\"k8s.pod.name\"]),\r\n    tostring(parse_json(MetricAttributes)[\"pod\"]),\r\n    iif(\r\n        isnotempty(parse_json(ResourceAttributes)[\"server.address\"]),\r\n        strcat(split(tostring(parse_json(ResourceAttributes)[\"server.address\"]), \".\")[0], \"-*\"),\r\n        \"\"\r\n    )\r\n  )\r\n| project Timestamp, Namespace, Pod, MetricName , MetricValue, MetricType, MetricAttributes, ResourceAttributes\r\n| take 1000",
       "querySource": "raw"
      }
     ]
    }
   ]
  }
 ]
}