{
 "title": "Network Monitoring - Pixie",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Data source",
    "query": "grafana-azure-data-explorer-datasource"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| where MetricName == \"k8s.pod.cpu.utilization\"\r\n| extend NamespaceName = tostring(parse_json(ResourceAttributes)[\"k8s.namespace.name\"])\r\n| project NamespaceName"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| where MetricName == \"k8s.pod.cpu.utilization\"\r\n| extend NamespaceName = tostring(parse_json(ResourceAttributes)[\"k8s.namespace.name\"])\r\n| extend PodName = tostring(parse_json(ResourceAttributes)[\"k8s.pod.name\"])\r\n| where NamespaceName == \"${namespace}\"\r\n| project PodName"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Bytes Recieved for pod ${pod} in namespace ${namespace}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| extend PixieMetric = tostring(parse_json(ResourceAttributes)[\"px.cloud.address\"])\r\n| where PixieMetric == \"getcosmic.ai:443\"\r\n| where MetricName == \"network_stats.rx_bytes\"\r\n| extend PodName = split(tostring(parse_json(ResourceAttributes)[\"k8s.pod.name\"]), \"/\")[1]\r\n| extend NamespaceName = split(tostring(parse_json(ResourceAttributes)[\"k8s.pod.name\"]), \"/\")[0]\r\n| where PodName == \"${pod}\"\r\n| summarize arg_max(Timestamp, MetricValue) by bin(Timestamp, 1m)  // one data point per minute\r\n| order by Timestamp asc\r\n| serialize\r\n| extend PrevValue = prev(MetricValue), PrevTimestamp = prev(Timestamp)\r\n| extend TimeDiffSeconds = datetime_diff('second', Timestamp, PrevTimestamp)\r\n| extend Rate = iif(isnotnull(PrevValue) and TimeDiffSeconds > 0, (MetricValue - PrevValue) / TimeDiffSeconds, double(null))\r\n| project Timestamp, Rate",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Bytes Transmitted by the pod ${pod} in namespace ${namespace}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| extend PixieMetric = tostring(parse_json(ResourceAttributes)[\"px.cloud.address\"])\r\n| where PixieMetric == \"getcosmic.ai:443\"\r\n| where MetricName == \"network_stats.tx_bytes\"\r\n| extend PodName = split(tostring(parse_json(ResourceAttributes)[\"k8s.pod.name\"]), \"/\")[1]\r\n| extend NamespaceName = split(tostring(parse_json(ResourceAttributes)[\"k8s.pod.name\"]), \"/\")[0]\r\n| where PodName == \"${pod}\"\r\n| summarize arg_max(Timestamp, MetricValue) by bin(Timestamp, 1m)\r\n| order by Timestamp asc\r\n| serialize\r\n| extend PrevValue = prev(MetricValue), PrevTimestamp = prev(Timestamp)\r\n| extend TimeDiffSeconds = datetime_diff('second', Timestamp, PrevTimestamp)\r\n| extend Rate = iif(isnotnull(PrevValue) and TimeDiffSeconds > 0, (MetricValue - PrevValue) / TimeDiffSeconds, double(null))\r\n| project Timestamp, Rate",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Packets Recieved by the pod ${pod} in namespace ${namespace}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| extend PixieMetric = tostring(parse_json(ResourceAttributes)[\"px.cloud.address\"])\r\n| where PixieMetric == \"getcosmic.ai:443\"\r\n| where MetricName == \"network_stats.rx_packets\"\r\n| extend \r\n    PodName = split(tostring(parse_json(ResourceAttributes)[\"k8s.pod.name\"]), \"/\")[1],\r\n    NamespaceName = split(tostring(parse_json(ResourceAttributes)[\"k8s.pod.name\"]), \"/\")[0]\r\n| where PodName == \"${pod}\"\r\n| project Timestamp, PodName, NamespaceName, MetricValue\r\n| order by Timestamp asc\r\n| serialize\r\n| extend PrevTimestamp = prev(Timestamp), PrevValue = prev(MetricValue)\r\n| extend TimeDiffSeconds = datetime_diff('second', Timestamp, PrevTimestamp)\r\n| extend Derivative = iif(isnull(PrevValue) or TimeDiffSeconds == 0, real(null), (MetricValue - PrevValue) / TimeDiffSeconds)\r\n| project Timestamp, PodName, NamespaceName, Derivative",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Packets Transmitted by the pod ${pod} in namespace ${namespace}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| extend PixieMetric = tostring(parse_json(ResourceAttributes)[\"px.cloud.address\"])\r\n| where PixieMetric == \"getcosmic.ai:443\"\r\n| where MetricName == \"network_stats.tx_packets\"\r\n| extend PodName = split(tostring(parse_json(ResourceAttributes)[\"k8s.pod.name\"]), \"/\")[1]\r\n| extend NamespaceName = split(tostring(parse_json(ResourceAttributes)[\"k8s.pod.name\"]), \"/\")[0]\r\n| where PodName == \"${pod}\"\r\n| summarize arg_max(Timestamp, MetricValue) by bin(Timestamp, 1m)\r\n| order by Timestamp asc\r\n| serialize\r\n| extend PrevValue = prev(MetricValue), PrevTimestamp = prev(Timestamp)\r\n| extend TimeDiffSeconds = datetime_diff('second', Timestamp, PrevTimestamp)\r\n| extend Rate = iif(isnotnull(PrevValue) and TimeDiffSeconds > 0, (MetricValue - PrevValue) / TimeDiffSeconds, double(null))\r\n| project Timestamp, Rate",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Network Errors Recieved by the pod ${pod} in namespace ${namespace}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| extend PixieMetric = tostring(parse_json(ResourceAttributes)[\"px.cloud.address\"])\r\n| where PixieMetric == \"getcosmic.ai:443\"\r\n| where MetricName == \"network_stats.rx_errors\"\r\n| extend PodName = split(tostring(parse_json(ResourceAttributes)[\"k8s.pod.name\"]), \"/\")[1]\r\n| extend NamespaceName = split(tostring(parse_json(ResourceAttributes)[\"k8s.pod.name\"]), \"/\")[0]\r\n| where PodName == \"${pod}\"\r\n| summarize arg_max(Timestamp, MetricValue) by bin(Timestamp, 1m)\r\n| order by Timestamp asc\r\n| serialize\r\n| extend PrevValue = prev(MetricValue), PrevTimestamp = prev(Timestamp)\r\n| extend TimeDiffSeconds = datetime_diff('second', Timestamp, PrevTimestamp)\r\n| extend Rate = iif(isnotnull(PrevValue) and TimeDiffSeconds > 0, (MetricValue - PrevValue) / TimeDiffSeconds, double(null))\r\n| project Timestamp, Rate",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Network Errors Transmitted by the pod ${pod} in namespace ${namespace}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| extend PixieMetric = tostring(parse_json(ResourceAttributes)[\"px.cloud.address\"])\r\n| where PixieMetric == \"getcosmic.ai:443\"\r\n| where MetricName == \"network_stats.tx_errors\"\r\n| extend PodName = split(tostring(parse_json(ResourceAttributes)[\"k8s.pod.name\"]), \"/\")[1]\r\n| extend NamespaceName = split(tostring(parse_json(ResourceAttributes)[\"k8s.pod.name\"]), \"/\")[0]\r\n| where PodName == \"${pod}\"\r\n| summarize arg_max(Timestamp, MetricValue) by bin(Timestamp, 1m)\r\n| order by Timestamp asc\r\n| serialize\r\n| extend PrevValue = prev(MetricValue), PrevTimestamp = prev(Timestamp)\r\n| extend TimeDiffSeconds = datetime_diff('second', Timestamp, PrevTimestamp)\r\n| extend Rate = iif(isnotnull(PrevValue) and TimeDiffSeconds > 0, (MetricValue - PrevValue) / TimeDiffSeconds, double(null))\r\n| project Timestamp, Rate",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Network Drops Recieved by the pod ${pod} in namespace ${namespace}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| extend PixieMetric = tostring(parse_json(ResourceAttributes)[\"px.cloud.address\"])\r\n| where PixieMetric == \"getcosmic.ai:443\"\r\n| where MetricName == \"network_stats.rx_drops\"\r\n| extend PodName = split(tostring(parse_json(ResourceAttributes)[\"k8s.pod.name\"]), \"/\")[1]\r\n| extend NamespaceName = split(tostring(parse_json(ResourceAttributes)[\"k8s.pod.name\"]), \"/\")[0]\r\n| where PodName == \"${pod}\"\r\n| summarize arg_max(Timestamp, MetricValue) by bin(Timestamp, 1m)\r\n| order by Timestamp asc\r\n| serialize\r\n| extend PrevValue = prev(MetricValue), PrevTimestamp = prev(Timestamp)\r\n| extend TimeDiffSeconds = datetime_diff('second', Timestamp, PrevTimestamp)\r\n| extend Rate = iif(isnotnull(PrevValue) and TimeDiffSeconds > 0, (MetricValue - PrevValue) / TimeDiffSeconds, double(null))\r\n| project Timestamp, Rate",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Network Drops Transmitted by the pod ${pod} in namespace ${namespace}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| extend PixieMetric = tostring(parse_json(ResourceAttributes)[\"px.cloud.address\"])\r\n| where PixieMetric == \"getcosmic.ai:443\"\r\n| where MetricName == \"network_stats.tx_drops\"\r\n| extend PodName = split(tostring(parse_json(ResourceAttributes)[\"k8s.pod.name\"]), \"/\")[1]\r\n| extend NamespaceName = split(tostring(parse_json(ResourceAttributes)[\"k8s.pod.name\"]), \"/\")[0]\r\n| where PodName == \"${pod}\"\r\n| summarize arg_max(Timestamp, MetricValue) by bin(Timestamp, 1m)\r\n| order by Timestamp asc\r\n| serialize\r\n| extend PrevValue = prev(MetricValue), PrevTimestamp = prev(Timestamp)\r\n| extend TimeDiffSeconds = datetime_diff('second', Timestamp, PrevTimestamp)\r\n| extend Rate = iif(isnotnull(PrevValue) and TimeDiffSeconds > 0, (MetricValue - PrevValue) / TimeDiffSeconds, double(null))\r\n| project Timestamp, Rate",
     "querySource": "raw"
    }
   ]
  }
 ]
}