{
 "title": "Kubernetes / Compute Resources / Pod",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Data source",
    "query": "grafana-azure-data-explorer-datasource"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| where MetricName == \"k8s.pod.cpu.utilization\"\r\n| extend NamespaceName = tostring(parse_json(ResourceAttributes)[\"k8s.namespace.name\"])\r\n| project NamespaceName"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| where MetricName == \"k8s.pod.cpu.utilization\"\r\n| extend NamespaceName = tostring(parse_json(ResourceAttributes)[\"k8s.namespace.name\"])\r\n| extend PodName = tostring(parse_json(ResourceAttributes)[\"k8s.pod.name\"])\r\n| where NamespaceName == \"${namespace}\"\r\n| project PodName"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| where MetricName == \"kube_pod_container_resource_limits\"\r\n| extend ResourceType = tostring(parse_json(MetricAttributes)[\"resource\"])\r\n| extend PodName = tostring(parse_json(MetricAttributes)[\"pod\"])\r\n| extend NamespaceName = tostring(parse_json(MetricAttributes)[\"namespace\"])\r\n| where NamespaceName == \"${namespace}\"\r\n| where PodName == \"${pod}\"\r\n| where ResourceType == \"cpu\"\r\n| summarize avg_cpu_util = avg(MetricValue) by bin(Timestamp, 1m), PodName",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\n| where $__timeFilter(Timestamp)\n| where MetricName == \"kube_pod_container_resource_requests\"\n| extend Container = tostring(parse_json(ResourceAttributes)[\"container.name\"])\n| extend Namespace = tostring(parse_json(MetricAttributes)[\"namespace\"])\n| extend Pod = tostring(parse_json(MetricAttributes)[\"pod\"])\n| where Namespace == \"${namespace}\" and Pod == \"${pod}\"\n| summarize avg(MetricValue) by bin(Timestamp, 1m), Container\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\n| where $__timeFilter(Timestamp)\n| where MetricName == \"kube_pod_container_resource_limits\"\n| extend Container = tostring(parse_json(ResourceAttributes)[\"container.name\"])\n| extend Namespace = tostring(parse_json(MetricAttributes)[\"namespace\"])\n| extend Pod = tostring(parse_json(MetricAttributes)[\"pod\"])\n| where Namespace == \"${namespace}\" and Pod == \"${pod}\"\n| summarize avg(MetricValue) by bin(Timestamp, 1m), Container\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Memory Usage (WSS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\n| where $__timeFilter(Timestamp)\n| where MetricName == \"container.memory.working_set\"\n| extend Container = tostring(parse_json(ResourceAttributes)[\"container.name\"])\n| extend Namespace = tostring(parse_json(ResourceAttributes)[\"k8s.namespace.name\"])\n| extend Pod = tostring(parse_json(ResourceAttributes)[\"k8s.pod.name\"])\n| where Namespace == \"${namespace}\" and Pod == \"${pod}\"\n| summarize avg(MetricValue) by bin(Timestamp, 1m), Container\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\n| where $__timeFilter(Timestamp)\n| where MetricName == \"container_network_receive_bytes_total\"\n| extend Pod = tostring(parse_json(MetricAttributes)[\"container_label_io_kubernetes_pod_name\"])\n| extend Namespace = tostring(parse_json(MetricAttributes)[\"container_label_io_kubernetes_pod_namespace\"])\n| where Namespace == \"${namespace}\" and Pod == \"${pod}\"\n| summarize avg(MetricValue) by bin(Timestamp, 1m), Pod",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\n| where $__timeFilter(Timestamp)\n| where MetricName == \"container_network_transmit_bytes_total\"\n| extend Pod = tostring(parse_json(MetricAttributes)[\"container_label_io_kubernetes_pod_name\"])\n| extend Namespace = tostring(parse_json(MetricAttributes)[\"container_label_io_kubernetes_pod_namespace\"])\n| where Namespace == \"${namespace}\" and Pod == \"${pod}\"\n| summarize avg(MetricValue) by bin(Timestamp, 1m), Pod\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "IOPS (Read)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\n| where $__timeFilter(Timestamp)\n| where MetricName == \"container_fs_reads_total\"\n| extend Container = tostring(parse_json(ResourceAttributes)[\"container.name\"])\n| extend Namespace = tostring(parse_json(MetricAttributes)[\"container_label_io_kubernetes_pod_namespace\"])\n| extend Pod = tostring(parse_json(MetricAttributes)[\"container_label_io_kubernetes_pod_name\"])\n| where Namespace == \"${namespace}\" and Pod == \"${pod}\"\n| summarize avg(MetricValue) by bin(Timestamp, 1m), Container\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "IOPS (Write)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "\nOTELMetrics\n| where $__timeFilter(Timestamp)\n| where MetricName == \"container_fs_writes_total\"\n| extend Container = tostring(parse_json(ResourceAttributes)[\"container.name\"])\n| extend Namespace = tostring(parse_json(MetricAttributes)[\"container_label_io_kubernetes_pod_namespace\"])\n| extend Pod = tostring(parse_json(MetricAttributes)[\"container_label_io_kubernetes_pod_name\"])\n| where Namespace == \"${namespace}\" and Pod == \"${pod}\"\n| summarize avg(MetricValue) by bin(Timestamp, 1m), Container\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Disk Throughput (Read)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\n| where $__timeFilter(Timestamp)\n| where MetricName == \"container_fs_reads_bytes_total\"\n| extend Container = tostring(parse_json(ResourceAttributes)[\"container.name\"])\n| extend Namespace = tostring(parse_json(MetricAttributes)[\"container_label_io_kubernetes_pod_namespace\"])\n| extend Pod = tostring(parse_json(MetricAttributes)[\"container_label_io_kubernetes_pod_name\"])\n| where Namespace == \"${namespace}\" and Pod == \"${pod}\"\n| summarize avg(MetricValue) by bin(Timestamp, 1m), Container\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Disk Throughput (Write)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\n| where $__timeFilter(Timestamp)\n| where MetricName == \"container_fs_writes_bytes_total\"\n| extend Container = tostring(parse_json(ResourceAttributes)[\"container.name\"])\n| extend Namespace = tostring(parse_json(MetricAttributes)[\"container_label_io_kubernetes_pod_namespace\"])\n| extend Pod = tostring(parse_json(MetricAttributes)[\"container_label_io_kubernetes_pod_name\"])\n| where Namespace == \"${namespace}\" and Pod == \"${pod}\"\n| summarize avg(MetricValue) by bin(Timestamp, 1m), Container\n",
     "querySource": "raw"
    }
   ]
  }
 ]
}