{
 "title": "OTEL Demo Application Status",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Errors Distribution",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body !contains \"UNIQUE\"\n| where SeverityText == \"ERROR\"\n| where ResourceAttributes != \"{}\"\n| extend ServiceName = tostring(ResourceAttributes[\"service.name\"])\n| extend CodeFilePath = tostring(LogsAttributes[\"code.filepath\"])\n| extend CodeFunction = tostring(LogsAttributes[\"code.function\"])\n| extend CodeLineNumber = tostring(LogsAttributes[\"code.lineno\"])\n| where ServiceName in ('accounting','ad', 'cart', 'checkout', 'currency', 'email', 'flagd', 'fraud-detection', 'frontend', 'frontend-proxy', 'frontend-web', 'image-provider', 'load-generator', 'payment', 'quote', 'recommendation', 'shipping')\n| summarize ErrorCount = count() by bin(Timestamp, 1d)\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">General</h1>"
   }
  },
  {
   "title": "Total Info Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body !contains (\"UNIQUE\")\n| where SeverityText == 'INFO'\n| where ResourceAttributes != \"{}\"\n| extend ServiceName = tostring(ResourceAttributes.['service.name'])\n| extend CodeFilePath = tostring(LogsAttributes.['code.filepath'])\n| extend CodeFunction = tostring(LogsAttributes.['code.function'])\n| extend CodeLineNumber = tostring(LogsAttributes.['code.lineno'])\n| where ServiceName in ('accounting','ad', 'cart', 'checkout', 'currency', 'email', 'flagd', 'fraud-detection', 'frontend', 'frontend-proxy', 'frontend-web', 'image-provider', 'load-generator', 'payment', 'quote', 'recommendation', 'shipping')\n| count",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Warn Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body !contains (\"UNIQUE\")\n| where SeverityText == 'WARN'\n| where ResourceAttributes != \"{}\"\n| extend ServiceName = tostring(ResourceAttributes.['service.name'])\n| extend CodeFilePath = tostring(LogsAttributes.['code.filepath'])\n| extend CodeFunction = tostring(LogsAttributes.['code.function'])\n| extend CodeLineNumber = tostring(LogsAttributes.['code.lineno'])\n| where ServiceName in ('accounting','ad', 'cart', 'checkout', 'currency', 'email', 'flagd', 'fraud-detection', 'frontend', 'frontend-proxy', 'frontend-web', 'image-provider', 'load-generator', 'payment', 'quote', 'recommendation', 'shipping')\n| count",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Errors Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body !contains (\"UNIQUE\")\n| where SeverityText == 'ERROR'\n| where ResourceAttributes != \"{}\"\n| extend ServiceName = tostring(ResourceAttributes.['service.name'])\n| extend CodeFilePath = tostring(LogsAttributes.['code.filepath'])\n| extend CodeFunction = tostring(LogsAttributes.['code.function'])\n| extend CodeLineNumber = tostring(LogsAttributes.['code.lineno'])\n| where ServiceName in ('accounting','ad', 'cart', 'checkout', 'currency', 'email', 'flagd', 'fraud-detection', 'frontend', 'frontend-proxy', 'frontend-web', 'image-provider', 'load-generator', 'payment', 'quote', 'recommendation', 'shipping')\n| count",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Severity Logs",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body !contains (\"UNIQUE\")\n| where SeverityText != ''\n| where ResourceAttributes != \"{}\"\n| extend ServiceName = tostring(ResourceAttributes.['service.name'])\n| where ServiceName in ('accounting','ad', 'cart', 'checkout', 'currency', 'email', 'flagd', 'fraud-detection', 'frontend', 'frontend-proxy', 'frontend-web', 'image-provider', 'load-generator', 'payment', 'quote', 'recommendation', 'shipping')\n| summarize INFO = countif(SeverityText == 'INFO'), WARN = countif(SeverityText == 'WARN'), ERROR = countif(SeverityText == 'ERROR')\n\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total INFO",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body !contains (\"UNIQUE\")\n| where SeverityText == 'INFO'\n| where ResourceAttributes != \"{}\"\n| extend ServiceName = tostring(ResourceAttributes.['service.name'])\n| extend CodeFilePath = tostring(LogsAttributes.['code.filepath'])\n| extend CodeFunction = tostring(LogsAttributes.['code.function'])\n| extend CodeLineNumber = tostring(LogsAttributes.['code.lineno'])\n| where ServiceName in ('accounting','ad', 'cart', 'checkout', 'currency', 'email', 'flagd', 'fraud-detection', 'frontend', 'frontend-proxy', 'frontend-web', 'image-provider', 'load-generator', 'payment', 'quote', 'recommendation', 'shipping')\n| order by Timestamp desc\n| project Timestamp, TraceID, SpanID, Body, ServiceName, CodeFilePath, CodeFunction, CodeLineNumber",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Warnings",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body !contains (\"UNIQUE\")\n| where SeverityText == 'WARN'\n| where ResourceAttributes != \"{}\"\n| extend ServiceName = tostring(ResourceAttributes.['service.name'])\n| extend CodeFilePath = tostring(LogsAttributes.['code.filepath'])\n| extend CodeFunction = tostring(LogsAttributes.['code.function'])\n| extend CodeLineNumber = tostring(LogsAttributes.['code.lineno'])\n| where ServiceName in ('accounting','ad', 'cart', 'checkout', 'currency', 'email', 'flagd', 'fraud-detection', 'frontend', 'frontend-proxy', 'frontend-web', 'image-provider', 'load-generator', 'payment', 'quote', 'recommendation', 'shipping')\n| project Timestamp, TraceID, SpanID, Body, ServiceName, CodeFilePath, CodeFunction, CodeLineNumber",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body !contains (\"UNIQUE\")\n| where SeverityText == 'ERROR'\n| where ResourceAttributes != \"{}\"\n| extend ServiceName = tostring(ResourceAttributes.['service.name'])\n| extend CodeFilePath = tostring(LogsAttributes.['code.filepath'])\n| extend CodeFunction = tostring(LogsAttributes.['code.function'])\n| extend CodeLineNumber = tostring(LogsAttributes.['code.lineno'])\n| where ServiceName in ('accounting','ad', 'cart', 'checkout', 'currency', 'email', 'flagd', 'fraud-detection', 'frontend', 'frontend-proxy', 'frontend-web', 'image-provider', 'load-generator', 'payment', 'quote', 'recommendation', 'shipping')\n| project Timestamp, TraceID, SpanID, Body, ServiceName, CodeFilePath, CodeFunction, CodeLineNumber",
     "querySource": "raw"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">Metrics</h1>"
   }
  },
  {
   "title": "Latency status",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELTraces\n| where $__timeFilter(StartTime)\n| extend Latency = EndTime - StartTime\n| extend ServiceName = tostring(ResourceAttributes.['service.name'])\n| where not(ServiceName contains \"UI\")\n| where ServiceName in ('accounting','ad', 'cart', 'checkout', 'currency', 'email', 'flagd', 'fraud-detection', 'frontend', 'frontend-proxy', 'frontend-web', 'image-provider', 'load-generator', 'payment', 'quote', 'recommendation', 'shipping')\n| summarize arg_max(Latency, *) by TraceID\n| project ServiceName, Latency, SpanID, TraceID\n| sort by Latency desc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\n| where $__timeFilter(Timestamp)\n| where MetricName == 'k8s.pod.cpu.utilization'\n| extend PodName = parse_json(ResourceAttributes)['k8s.pod.name']\n| extend PodNamespace = parse_json(ResourceAttributes)['k8s.namespace.name']\n| where PodNamespace == 'otel-demo'\n| order by Timestamp desc\n| summarize by tostring(PodName), MetricValue, Timestamp",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\n| where $__timeFilter(Timestamp)\n| where MetricName == 'k8s.pod.memory.usage'\n| extend PodName = parse_json(ResourceAttributes)['k8s.pod.name']\n| extend PodNamespace = parse_json(ResourceAttributes)['k8s.namespace.name']\n| where PodNamespace == 'otel-demo'\n| order by Timestamp desc\n| summarize by tostring(PodName), MetricValue, Timestamp",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\n| where $__timeFilter(Timestamp)\n| where MetricName == 'k8s.pod.network.io'\n| extend PodName = parse_json(ResourceAttributes)['k8s.pod.name']\n| extend PodNamespace = parse_json(ResourceAttributes)['k8s.namespace.name']\n| where PodNamespace == 'otel-demo'\n| order by Timestamp desc\n| summarize by tostring(PodName), MetricValue, Timestamp",
     "querySource": "raw"
    }
   ]
  }
 ]
}