{
 "title": "Cart Service Exemplars",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard shows the use of metric exemplars.\nExemplars can be used to look up a trace in Jaeger.\nOnly the most recent exemplars may still be available in Jaeger.\n<br>\nChart panels may require 5 minutes after the Demo is started before rendering data."
   }
  },
  { "title": "GetCart Exemplars", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "GetCart Latency Heatmap with Exemplars",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| where MetricName == \"app.cart.get_cart.latency_bucket\"\r\n| extend le = todouble(parse_json(MetricAttributes)[\"le\"])\r\n| summarize Count = sum(MetricValue) by bin(Timestamp, 1m), le",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "95th Pct Cart GetCart Latency with Exemplars",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELTraces\r\n| where $__timeFilter(StartTime)\r\n| extend \r\n    ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"]),\r\n    SpanName = tostring(SpanName),\r\n    DurationMs = datetime_diff(\"millisecond\", EndTime, StartTime)\r\n| where ServiceName == \"cart\" and SpanName contains \"GetCart\"\r\n| summarize AvgLatency = avg(DurationMs) by bin(StartTime, 1m)\r\n| project Timestamp = StartTime, AvgLatency",
     "querySource": "raw"
    }
   ]
  },
  { "title": "AddItem Exemplars", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "AddItem Latency Heatmap with Exemplars",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| where MetricName == \"app.cart.add_item.latency_bucket\"\r\n| extend le = todouble(parse_json(MetricAttributes)[\"le\"])\r\n| summarize Count = sum(MetricValue) by bin(Timestamp, 1m), le",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "95th Pct Cart AddItem Latency with Exemplars",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELTraces\r\n| where $__timeFilter(StartTime)\r\n| extend \r\n    ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"]),\r\n    SpanName = tostring(SpanName),\r\n    DurationMs = datetime_diff(\"millisecond\", EndTime, StartTime)\r\n| where ServiceName == \"cart\" and SpanName contains \"AddItem\"\r\n| summarize AvgLatency = avg(DurationMs) by bin(StartTime, 1m)\r\n| project Timestamp = StartTime, AvgLatency",
     "querySource": "raw"
    }
   ]
  }
 ]
}