{
 "title": "Demo Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "OTELTraces\r\n| where $__timeFilter(StartTime)\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| summarize count()by ServiceName\r\n| where ServiceName in ('accounting','ad', 'cart', 'checkout', 'currency', 'email', 'flagd', 'fraud-detection', 'frontend', 'frontend-proxy', 'frontend-web', 'image-provider', 'load-generator', 'payment', 'quote', 'recommendation', 'shipping')\r\n| project ServiceName"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard shows RED metrics for the selected service, as generated by the spanmetrics connector in the OpenTelemetry Collector.\nIf the selected service emits logs, the logs will also be displayed.\nCustom metrics generated by some services are also displayed. \n<br/>\nChart panels may require 5 minutes after the Demo is started before rendering data."
   }
  },
  { "title": "Spanmetrics (RED metrics)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Requests Rate by Span Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| where MetricName == \"traces.span.metrics.duration_count\"\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| extend SpanName = tostring(parse_json(MetricAttributes)[\"span.name\"])\r\n| where ServiceName == \"${service}\"\r\n| summarize rate = sum(MetricValue) by bin(Timestamp, 1m), SpanName",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Error Rate by Span Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| where MetricName == \"traces.span.metrics.calls\"\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| extend SpanName = tostring(parse_json(MetricAttributes)[\"span.name\"])\r\n| extend StatusCode = tostring(parse_json(MetricAttributes)[\"status.code\"])\r\n| where ServiceName == \"${service}\" and StatusCode == \"STATUS_CODE_ERROR\"\r\n| summarize error_rate = sum(MetricValue) by bin(Timestamp, 1m), SpanName",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Average Duration by Span Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELTraces\r\n| where $__timeFilter(StartTime)\r\n| extend \r\n    ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"]),\r\n    SpanName = SpanName,\r\n    DurationMs = datetime_diff(\"millisecond\", EndTime, StartTime)\r\n| where ServiceName == \"${service}\"\r\n| summarize avg(DurationMs) by bin(StartTime, 1m), SpanName\r\n| project Timestamp = StartTime, SpanName, AvgDurationMs = avg_DurationMs",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Application Log Records", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Log Records by Severity",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 13 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\r\n| where $__timeFilter(Timestamp)\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| extend Severity = tostring(SeverityText)\r\n| where ServiceName == \"${service}\"\r\n| summarize Count = count() by Severity",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Log Records (100 recent entries)",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 13 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\r\n| where $__timeFilter(Timestamp)\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| where ServiceName == \"${service}\"\r\n| sort by Timestamp desc\r\n| take 100",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Python services (CPU%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| where MetricName == \"process.runtime.cpython.cpu_time\"\r\n| extend Type = tostring(parse_json(MetricAttributes)[\"type\"])\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| where ServiceName == \"${service}\"\r\n| summarize AvgCpuTime = avg(MetricValue) by bin(Timestamp, 1m), Type",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Python services (Memory)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| where MetricName == \"process.runtime.cpython.memory\"\r\n| extend Type = tostring(parse_json(MetricAttributes)[\"type\"])\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| where ServiceName == \"${service}\" and Type == \"rss\"\r\n| summarize AvgMemoryBytes = avg(MetricValue) by bin(Timestamp, 1m)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Recommendations Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| where MetricName == \"app_recommendations_counter\"\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| where ServiceName == \"${service}\"\r\n| summarize Rate = max(MetricValue) - min(MetricValue) by bin(Timestamp, 1m)",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Service Dependency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Service Dependency",
   "type": "nodeGraph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 39 },
   "targets": [
    { "service": "load-generator" }
   ]
  }
 ]
}