{
 "title": "Spanmetrics Demo Dashboard",
 "description": "Spanmetrics way of demo application view.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "OTELTraces\r\n| where $__timeFilter(StartTime)\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| summarize count()by ServiceName\r\n| where ServiceName in ('accounting','ad', 'cart', 'checkout', 'currency', 'email', 'flagd', 'fraud-detection', 'frontend', 'frontend-proxy', 'frontend-web', 'image-provider', 'load-generator', 'payment', 'quote', 'recommendation', 'shipping')\r\n| project ServiceName"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard uses RED metrics generated for all services by the spanmetrics connector configured in the OpenTelemetry Collector.\n<br>\nChart panels may require 5 minutes after the Demo is started before rendering data."
   }
  },
  {
   "title": "Service Level - Throughput and Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Top 3x3 - Service Latency - quantile95",
   "type": "gauge",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| where MetricName == \"traces.span.metrics.duration_bucket\"\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| summarize avg(MetricValue) by bin(Timestamp, 1m), ServiceName",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Top 7 Services Mean Rate over Range",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| where MetricName == \"traces.span.metrics.calls\"\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| summarize avg(MetricValue) by bin(Timestamp, 1m), ServiceName",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Top 7 Services Mean ERROR Rate over Range",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| where MetricName == \"traces.span.metrics.calls\"\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| summarize avg(MetricValue) by bin(Timestamp, 1m), ServiceName",
     "querySource": "raw"
    }
   ]
  },
  { "title": "span_names Level - Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Top 7 span_names and Errors  (APM Table)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| where MetricName == \"traces.span.metrics.calls\"\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| summarize avg(MetricValue) by bin(Timestamp, 1m), ServiceName",
     "querySource": "raw"
    }
   ]
  },
  { "title": "span_name Level - Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Top 3x3 - span_name Latency - quantile95",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| where MetricName == \"traces.span.metrics.duration_bucket\"\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| summarize avg(MetricValue) by bin(Timestamp, 1m), ServiceName",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Top 7 Highest Endpoint Latencies  Mean Over Range ",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\r\n| where $__timeFilter(Timestamp)\r\n| where MetricName == \"traces.span.metrics.duration_count\"\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| summarize avg(MetricValue) by bin(Timestamp, 1m), ServiceName",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Top 7 Latencies Over Range ",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELTraces\r\n| where $__timeFilter(StartTime)\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| extend SpanName = tostring(SpanName)\r\n| extend DurationMs = datetime_diff(\"millisecond\", EndTime, StartTime)\r\n| where ServiceName == \"${service}\"\r\n| summarize AvgLatencyMs = avg(DurationMs) by SpanName\r\n| top 7 by AvgLatencyMs desc",
     "querySource": "raw"
    }
   ]
  }
 ]
}