{
 "title": "Application Status",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">General</h1>"
   }
  },
  {
   "title": "Total Info Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body !contains (\"UNIQUE\")\n| where SeverityText == 'INFO'\n| where ResourceAttributes != \"{}\"\n| extend ServiceName = tostring(ResourceAttributes.['service.name'])\n| extend CodeFilePath = tostring(LogsAttributes.['code.filepath'])\n| extend CodeFunction = tostring(LogsAttributes.['code.function'])\n| extend CodeLineNumber = tostring(LogsAttributes.['code.lineno'])\n| count",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Warn Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body !contains (\"UNIQUE\")\n| where SeverityText == 'WARN'\n| where ResourceAttributes != \"{}\"\n| extend ServiceName = tostring(ResourceAttributes.['service.name'])\n| extend CodeFilePath = tostring(LogsAttributes.['code.filepath'])\n| extend CodeFunction = tostring(LogsAttributes.['code.function'])\n| extend CodeLineNumber = tostring(LogsAttributes.['code.lineno'])\n| count",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Errors Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body !contains (\"UNIQUE\")\n| where SeverityText == 'ERROR'\n| where ResourceAttributes != \"{}\"\n| extend ServiceName = tostring(ResourceAttributes.['service.name'])\n| extend CodeFilePath = tostring(LogsAttributes.['code.filepath'])\n| extend CodeFunction = tostring(LogsAttributes.['code.function'])\n| extend CodeLineNumber = tostring(LogsAttributes.['code.lineno'])\n| count",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Severity Logs",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body !contains (\"UNIQUE\")\n| where SeverityText != ''\n| where ResourceAttributes != \"{}\"\n| summarize INFO = countif(SeverityText == 'INFO'), WARN = countif(SeverityText == 'WARN'), ERROR = countif(SeverityText == 'ERROR')\n\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total INFO",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body !contains (\"UNIQUE\")\n| where SeverityText == 'INFO'\n| where ResourceAttributes != \"{}\"\n| extend ServiceName = tostring(ResourceAttributes.['service.name'])\n| extend CodeFilePath = tostring(LogsAttributes.['code.filepath'])\n| extend CodeFunction = tostring(LogsAttributes.['code.function'])\n| extend CodeLineNumber = tostring(LogsAttributes.['code.lineno'])\n| project Timestamp, TraceID, SpanID, Body, ServiceName, CodeFilePath, CodeFunction, CodeLineNumber",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Warnings",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body !contains (\"UNIQUE\")\n| where SeverityText == 'WARN'\n| where ResourceAttributes != \"{}\"\n| extend ServiceName = tostring(ResourceAttributes.['service.name'])\n| extend CodeFilePath = tostring(LogsAttributes.['code.filepath'])\n| extend CodeFunction = tostring(LogsAttributes.['code.function'])\n| extend CodeLineNumber = tostring(LogsAttributes.['code.lineno'])\n| project Timestamp, TraceID, SpanID, Body, ServiceName, CodeFilePath, CodeFunction, CodeLineNumber",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body !contains (\"UNIQUE\")\n| where SeverityText == 'ERROR'\n| where ResourceAttributes != \"{}\"\n| extend ServiceName = tostring(ResourceAttributes.['service.name'])\n| extend CodeFilePath = tostring(LogsAttributes.['code.filepath'])\n| extend CodeFunction = tostring(LogsAttributes.['code.function'])\n| extend CodeLineNumber = tostring(LogsAttributes.['code.lineno'])\n| project Timestamp, TraceID, SpanID, Body, ServiceName, CodeFilePath, CodeFunction, CodeLineNumber",
     "querySource": "raw"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">Usage</h1>"
   }
  },
  {
   "title": "Total User Service Calls",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 25 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\n| where $__timeFilter(Timestamp)\n| where MetricName == 'user_srv_http_requests_total'\n| summarize arg_max(Timestamp, *) by MetricName",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Order Service Calls",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\n| where $__timeFilter(Timestamp)\n| where MetricName == 'order_service_http_requests_total'\n| summarize arg_max(Timestamp, *) by MetricName",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Cart Service Calls",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\n| where $__timeFilter(Timestamp)\n| where MetricName == 'cart_service_http_requests_total'\n| summarize arg_max(Timestamp, *) by MetricName",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Service Calls",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 25 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\n| where $__timeFilter(Timestamp)\n| where MetricName contains 'http_requests_total'\n| summarize arg_max(Timestamp, *) by MetricName\n| project MetricName, MetricValue\n| evaluate pivot(MetricName, sum(MetricValue))",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Latency status",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELTraces\n| where $__timeFilter(StartTime)\n| extend Latency = EndTime - StartTime\n| extend ServiceName = tostring(ResourceAttributes.['service.name'])\n| where not(ServiceName contains \"UI\")\n| summarize arg_max(Latency, *) by TraceID\n| project ServiceName, Latency, SpanID, TraceID\n| sort by Latency desc",
     "querySource": "raw"
    }
   ]
  }
 ]
}