{
 "title": "Correlated Observability",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "jaeger", "label": "Jaeger Data Source", "query": "jaeger" },
   {
    "name": "adx",
    "label": "ADX Data Source",
    "query": "grafana-azure-data-explorer-datasource"
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "OTELTraces\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| summarize count()by ServiceName\r\n| project ServiceName"
    }
   },
   {
    "name": "timestamp",
    "label": "Time Of Error",
    "query": {
     "query": "let ErrorSpans = OTELTraces\r\n| where tolower(SpanStatus) == \"status_code_error\"\r\n| summarize ErrorSpans = count() by Time = bin(StartTime, 1m);\r\nlet ErrorLogs = OTELLogs\r\n| where tolower(SeverityText) in (\"error\", \"critical\")\r\n| summarize ErrorLogs = count() by Time = bin(Timestamp, 1m);\r\nlet CPUMetrics = OTELMetrics\r\n| where MetricName == \"container.cpu.utilization\"\r\n| summarize AvgCPU = avg(MetricValue) by Time = bin(Timestamp, 1m);\r\nErrorSpans\r\n| join kind=fullouter ErrorLogs on Time\r\n| join kind=fullouter CPUMetrics on Time\r\n| sort by Time desc\r\n| where ErrorSpans != \"\" or ErrorLogs != \"\"\r\n| project tostring(Time)"
    }
   },
   {
    "name": "trace",
    "label": "Trace ID",
    "query": {
     "query": "let SelectedTime = todatetime(\"${timestamp}\");\r\nOTELTraces\r\n| where StartTime between (SelectedTime - 30s .. SelectedTime + 30s)\r\n| sort by StartTime desc\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| where ServiceName == \"${service}\"\r\n| project TraceID"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Correlated Error Counts",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let ErrorSpans = OTELTraces\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| where tolower(SpanStatus) == \"status_code_error\"\r\n| summarize ErrorSpans = count() by ServiceName, Time = bin(StartTime, 1m);\r\n\r\nlet ErrorLogs = OTELLogs\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| where tolower(SeverityText) in (\"error\", \"critical\")\r\n| summarize ErrorLogs = count() by ServiceName, Time = bin(Timestamp, 1m);\r\n\r\nErrorSpans\r\n| join kind=fullouter ErrorLogs on Time, ServiceName\r\n| sort by Time asc\r\n| where ErrorSpans != \"\" or ErrorLogs != \"\"\r\n| where ServiceName != \"\"\r\n| project Time, ServiceName, ErrorSpans, ErrorLogs",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Tracing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "${service} Traces",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "database": "openteldb",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let SelectedTime = todatetime(\"${timestamp}\");\r\nOTELTraces\r\n| where StartTime between (SelectedTime - 30s .. SelectedTime + 30s)\r\n| sort by StartTime desc\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| where ServiceName == \"${service}\"\r\n| project StartTime, EndTime, TraceID, ServiceName",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Trace Data",
     "type": "traces",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 14 },
     "targets": [
      { "query": "${trace}" }
     ]
    }
   ]
  },
  {
   "title": "Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "${service} Logs",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "database": "openteldb",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "let SelectedTime = todatetime(\"${timestamp}\");\r\nOTELLogs\r\n| where Timestamp  between (SelectedTime - 30s .. SelectedTime + 30s)\r\n| sort by Timestamp desc\r\n| extend ServiceName = tostring(parse_json(ResourceAttributes)[\"service.name\"])\r\n| where ServiceName == \"${service}\"\r\n| sort by ServiceName desc\r\n| project Timestamp, ServiceName, SeverityText, Body",
       "querySource": "raw"
      }
     ]
    }
   ]
  }
 ]
}